apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/deployment.yaml
  - resources/ns.yaml
  - resources/service.yaml
  - resources/serviceaccount.yaml

namespace: hello-kubernetes
